- Dockerfile
- resources/loadtest/100-loadsubscriber.yaml
- resources/loadtest/500-sender.yaml
- resources/publisher/100-deployment.yaml
- resources/subscriber/300-deployments.yaml
> use ci-image in resources

- ci/eventing-tools-autobump-config.yaml
- add config for generic autobumper
> add autobump config

- ci/eventing-tools-autobump-config.yaml
- change pr title by using consistentImages:true
> use consistent images troughout all resources

- resources/validationtest/base/deployment.yaml
- resources/validationtest/base/functions.yaml
- resources/validationtest/base/subscriptions.yaml
Fix the resources of the validation test subscribers.
> Fix the resources of the validation test subscribers

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- NOTICE.md
- README.md
- add missing files to the repository: 
CONTRIBUTION
CODE_OF_CONDUCT
LICENSE
> add required .md files

- .github/workflows/unit-test-reusable.yml
- add a reusable generic GitHub action workflow for running unit tests.
https://github.com/kyma-project/eventing-manager/issues/361
> add a reusable unit test github action workflow

- .github/workflows/lint-go-reusable.yml
- config/lint/.golangci.yaml
- Modify Job name of centralized lint GitHub Action Workflow
- Lint fix: dupword
> Modify Job name

- config/lint/.golangci.yaml
> Lint Fix: tagalign

- config/lint/.golangci.yaml
> Lint Fix: gci

- config/lint/.golangci.yaml
- Add Prometheus for `gomoddirectives` white list (Allow redirect)
> Prometheus for gomoddirectives white list

- .github/dependabot.yml
- .github/workflows/lint-conventional-prs.yml
- internal/loadtest/sender/legacyevent/sender.go
> feat: add rules for PRs

- .gitignore
- Makefile
> chore: added make targets for lint

- .github/workflows/wait-build-reusable.yml
- rename wait-build-reusable.yml
> chore: rename wait-build-reusable.yml

- .github/workflows/build.yml
- .github/workflows/quality.yml
-  `build` and `code-quality` workflows will ignore changes in `external-images.yaml` file.
> fix: ignore changes to external-images.yaml in unrelated workflows

- external-images.yaml
- add images related to langfuse to `external images`
> chore: add langfuse images

- .github/workflows/unit-test-reusable-with-permission.yml
- adds an experimental unit test-workflow with explicit permissions
> feat: add unit test-workflow with explicit permissions

- external-images.yaml
- add `zookeeper` as an external image
> chore: add zookeeper to external images

- external-images.yaml
- add `python3.12-alpine3.21` to external images
> deps: add python3.12-alpine to external images

- external-images.yaml
- add image for golang24.1-alpine3.21
> chore: add image for golang24.1-alpine3.21

- .github/workflows/unit-test-reusable.yml
- Removed `metadata` field from permission. Not a valid field (https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions)
- This should fix failing tests on repo dependent on `eventing-tools`
- ...
> fix: remove invalid field 'metadata'

- external-images.yaml
> chore: added golang:1.24.7-alpine3.22
